### ISSUE TITLE
what to do on lost packets?

### ISSUE THREAD

**Issue by r-lyeh-archived** [flaxtonio/fntp-c#1]
how does the server tell the client the list of missing packets after client is done?

**Comment by VaheSa** [comment]
Client sends the UDP packages until the server sends the TCP end packege .
 the server checks using UDP package index and send end comand through TCP packege. 
we can discuss some more details in skype call (vahejet)

**Comment by r-lyeh-archived** [comment]
Yes I got that, but the remaining question about missing UDP packets is still pending.

Sample:
- Whole message is 5 packets long.
- Client sends ID+5 and waits for server ACK.
- Client sends packets #1,#2,#3,#4,#5 in order.
- Server receives packets #1,#4,#3,#5 in (that) order; packet #2 is lost forever (because shit happens).
- What does client do after sending all packets? Server won't tell to resend packet #2.
- What does server do after receiving #5? Will it block? #2 will never come.
- My only assumption is that client will have to loop forever the whole packet sequence (#1..#5) until server emits an end-command byte, but this case (and the packet-loss mechanism) is never commented on the spec. And that's my question.

PS: I think is more convenient to have this chat in public, so other people with the very same questions will eventually know about this.

**Comment by VaheSa** [comment]
Yes Client will have to loop forever the whole packets sequence (#1... #5) until server emits an end-command byte.
we think that this is not the best solution
what suggest to improve this logic?

**Comment by r-lyeh-archived** [comment]
Ok, thank you : )
